services:
  velxio:
    image: velxio-wasi:master
    container_name: velxio
    restart: unless-stopped

    ports:
      - "3080:80"

    environment:
      DATABASE_URL: sqlite+aiosqlite:////app/data/velxio.db
      DATA_DIR: /app/data
      IDF_PATH: /opt/esp-idf
      IDF_TOOLS_PATH: /root/.espressif
      ARDUINO_ESP32_PATH: /opt/arduino-esp32

      IDF_CCACHE_ENABLE: "1"
      CCACHE_DIR: /var/cache/ccache
      VELXIO_PERSISTENT_BUILD_DIR: "1"

    volumes:
      - ./data:/app/data
      - arduino-libs:/root/.arduino15
      - arduino-user-libs:/root/Arduino
      - ccache:/var/cache/ccache
      - velxio-build:/var/lib/velxio-build

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

volumes:
  arduino-libs:
  arduino-user-libs:
  ccache:
  velxio-build:
